[versions]
kotlin="2.3.0"
compose="1.10.0"
agp = "8.12.1"
camera2 = "1.3.2"
mlkit = "17.2.0"
maven-publish="0.34.0"
androidx-activity = "1.9.0"

[libraries]
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera2" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera2" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
mlkit = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit" }
kotlin-gp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id ="org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id ="org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }